export const mySkills: string[] = [

    'Accountability',
    'Agile methodologies',
    'Azure DevOps',
    'Azure Fundamentals',
    'Azure RGd',
    'Azure VMs',
    'Big picture',
    'Bitbucket',
    'Business Analysis',
    'Business Operations',
    'C#',
    'Calling out scopecreeps',
    'Can be diplomatic',
    'Can be direct',
    'Can be Friendly',
    'Client focus',
    'Confluence',
    'Creative problem solving',
    'Creative troubleshooting',
    'Critical issue resolution',
    'Critical thinking',
    'CSS',
    'Curiosity',
    'Deliverable scope knowledge',
    'Detail level',
    'Documentation',
    'DR',
    'Eagerness',
    'Emotional intelligence',
    'Empathy',
    'English',
    'Ergonomics',
    'Estimate collaboration',
    'Ethics',
    'Excel',
    'Excitement',
    'Extreme ownership',
    'Finance and Accounting',
    'Firmness',
    'Flagging operational issues',
    'Flagging project issues',
    'Focus',
    'Git',
    'Google docs',
    'Google Maps API',
    'Google sheets',
    'GraphQL',
    'High level documentation',
    'Hybrid',
    'Iaas',
    'IIS',
    'Integration',
    'Integration Platforms',
    'Integration testing',
    'Issue triaging',
    'JavaScript',
    'Jira',
    'JQuery',
    'Kanban',
    'Kendo UI',
    'Laziness',
    'Leadership',
    'Leadership',
    'Lean',
    'Learning to play guitar',
    'Learning to sing',
    'Legal',
    'Management',
    'Management',
    'Microservices',
    'Mssql server',
    'MVC',
    'MVVM',
    'New relic',
    'On call support',
    'Organizational structure',
    'Ownership',
    'Ownership',
    'Paas',
    'Pagerduty',
    'PoC',
    'Postman',
    'PowerPoint',
    'Product Development',
    'Product Support',
    'Project Management',
    'Project scope familiarity',
    'Quality',
    'Quality Assurance',
    'R&D',
    'RACI',
    'Requirement documentation',
    'Requirement gathering',
    'REST',
    'Role definition',
    'Russian',
    'SaaS',
    'Scrum',
    'Separation of concern',
    'Snagit',
    'SOAP',
    'SoapUI',
    'Solution Architecture',
    'SOW contribution, review',
    'SQL',
    'SQL geography',
    'Svn',
    'Team focus',
    'Tech leadership',
    'T-sql',
    'Typescript',
    'Unit testing',
    'Visio',
    'visual studio',
    'Visual studio code',
    'Waterfall',
    'WBS',
    'Web API',
    'Web Services',
    'Word',
    'Work delegation',
    'Work estimation',
    'Work Planning',
    'WPF',
    


];