export interface ISkill {
    name: string;
    id: string;
    tags: string;
    techtags: string;
    level: string;
}
export const mySkills: ISkill[] = [
    { "name": "Accountability", "id": "1", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Agile methodologies", "id": "2", "tags": "methodology", "techtags": "", "level": "" },
    { "name": "Azure DevOps", "id": "3", "tags": "tool", "techtags": "DevOps", "level": "1" },
    { "name": "Azure Fundamentals", "id": "4", "tags": "knowledge", "techtags": "Cloud Solutions", "level": "2" },
    { "name": "Azure RGs", "id": "5", "tags": "experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Azure VMs", "id": "6", "tags": "experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Big picture", "id": "7", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Bitbucket", "id": "8", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Business Analysis", "id": "9", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Business Operations", "id": "10", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "C#", "id": "11", "tags": "Programming Language", "techtags": "Backend", "level": "3" },
    { "name": "Calling out scopecreeps", "id": "12", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Can be diplomatic", "id": "13", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Can be direct", "id": "14", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Can be Friendly", "id": "15", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Client focus", "id": "16", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Confluence", "id": "17", "tags": "tool", "techtags": "", "level": "2" },
    { "name": "Creative problem solving", "id": "18", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Creative troubleshooting", "id": "19", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Critical issue resolution", "id": "20", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Critical thinking", "id": "21", "tags": "quality", "techtags": "", "level": "" },
    { "name": "CSS", "id": "22", "tags": "knowledge, experience, styling language", "techtags": "Frontend", "level": "1" },
    { "name": "Curiosity", "id": "23", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Deliverable scope knowledge", "id": "24", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Detail level", "id": "25", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Documentation", "id": "26", "tags": "ability", "techtags": "", "level": "" },
    { "name": "DR", "id": "27", "tags": "knowledge, experience", "techtags": "Operations", "level": "1" },
    { "name": "Eagerness", "id": "28", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Emotional intelligence", "id": "29", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Empathy", "id": "30", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "English", "id": "31", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Ergonomics", "id": "32", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Estimate collaboration", "id": "33", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Ethics", "id": "34", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Excel", "id": "35", "tags": "tool", "techtags": "Foundation", "level": "3" },
    { "name": "Excitement", "id": "36", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Extreme ownership", "id": "37", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Finance and Accounting", "id": "38", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "Firmness", "id": "39", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Flagging operational issues", "id": "40", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Flagging project issues", "id": "41", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Focus", "id": "42", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Git", "id": "43", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Google docs", "id": "44", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Google Maps API", "id": "45", "tags": "tool, R&D", "techtags": "Frontend", "level": "2" },
    { "name": "Google sheets", "id": "46", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "GraphQL", "id": "47", "tags": "knowledge", "techtags": "Integration", "level": "1" },
    { "name": "High level documentation", "id": "48", "tags": "ability", "techtags": "Solution Architecture", "level": "2" },
    { "name": "Hybrid", "id": "49", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Iaas", "id": "50", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "IIS", "id": "51", "tags": "knowledge, experience", "techtags": "Web Solutions", "level": "1" },
    { "name": "Integration", "id": "52", "tags": "knowledge, experience", "techtags": "Integration", "level": "2" },
    { "name": "Integration Platforms", "id": "53", "tags": "knowledge, experience", "techtags": "Integration", "level": "1" },
    { "name": "Integration testing", "id": "54", "tags": "knowledge, experience", "techtags": "Integration", "level": "1" },
    { "name": "Issue triaging", "id": "55", "tags": "ability", "techtags": "", "level": "" },
    { "name": "JavaScript", "id": "56", "tags": "Programming Language", "techtags": "Frontend, Backend", "level": "3" },
    { "name": "Jira", "id": "57", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "JQuery", "id": "58", "tags": "tech library, knowledge, experience", "techtags": "Frontend", "level": "1" },
    { "name": "Kanban", "id": "59", "tags": "tool", "techtags": "", "level": "" },
    { "name": "Kendo UI", "id": "60", "tags": "tech library, knowledge, experience", "techtags": "Frontend", "level": "2" },
    { "name": "Laziness", "id": "61", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Leadership", "id": "62", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Lean", "id": "63", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "Learning to play guitar", "id": "64", "tags": "ability, hobby", "techtags": "", "level": "" },
    { "name": "Learning to sing", "id": "65", "tags": "ability, hobby", "techtags": "", "level": "" },
    { "name": "Legal", "id": "66", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Management", "id": "67", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "Microservices", "id": "68", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Mssql server", "id": "69", "tags": "software, knowledge, experience", "techtags": "Data Management", "level": "2" },
    { "name": "MVC", "id": "70", "tags": "knowledge, experience", "techtags": "Architectural Patterns", "level": "2" },
    { "name": "MVVM", "id": "71", "tags": "knowledge, experience", "techtags": "Architectural Patterns", "level": "2" },
    { "name": "New relic", "id": "72", "tags": "tool", "techtags": "Infrastructure", "level": "1" },
    { "name": "On call support", "id": "73", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Organizational structure", "id": "74", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Ownership", "id": "75", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Paas", "id": "76", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Pagerduty", "id": "77", "tags": "tool", "techtags": "Operations", "level": "1" },
    { "name": "PoC", "id": "78", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Postman", "id": "79", "tags": "tool", "techtags": "Foundation, Web Solutions, Integration", "level": "1" },
    { "name": "PowerPoint", "id": "80", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Product Development", "id": "81", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Product Support", "id": "82", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Project Management", "id": "83", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Project scope familiarity", "id": "84", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Quality", "id": "85", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Quality Assurance", "id": "86", "tags": "ability", "techtags": "", "level": "" },
    { "name": "R&D", "id": "87", "tags": "ability", "techtags": "", "level": "" },
    { "name": "RACI", "id": "88", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Requirement documentation", "id": "89", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Requirement gathering", "id": "90", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "REST", "id": "91", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "2" },
    { "name": "Role definition", "id": "92", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Russian", "id": "93", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "SaaS", "id": "94", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Scrum", "id": "95", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "Separation of concern", "id": "96", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Snagit", "id": "97", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "SOAP", "id": "98", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "1" },
    { "name": "SoapUI", "id": "99", "tags": "tool", "techtags": "Foundation, Web Solutions, Integration", "level": "1" },
    { "name": "Solution Architecture", "id": "100", "tags": "knowledge, experience", "techtags": "", "level": "1" },
    { "name": "SOW contribution, review", "id": "101", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "SQL", "id": "102", "tags": "Quering Language", "techtags": "Data Management", "level": "2" },
    { "name": "SQL geography", "id": "103", "tags": "knowledge, experience", "techtags": "Data Management", "level": "1" },
    { "name": "Svn", "id": "104", "tags": "tool", "techtags": "Foundation", "level": "1" },
    { "name": "Team focus", "id": "105", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Tech leadership", "id": "106", "tags": "ability", "techtags": "", "level": "" },
    { "name": "T-sql", "id": "107", "tags": "Quering Language", "techtags": "Data Management", "level": "2" },
    { "name": "Typescript", "id": "108", "tags": "Programming Language", "techtags": "Foundation, Advanced", "level": "2" },
    { "name": "Unit testing", "id": "109", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Visio", "id": "110", "tags": "tool", "techtags": "Solution Architecture", "level": "2" },
    { "name": "Visual Studio", "id": "111", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Visual Studio Code", "id": "112", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Waterfall", "id": "113", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "WBS", "id": "114", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Web API", "id": "115", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "2" },
    { "name": "Web Services", "id": "116", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "1" },
    { "name": "Word", "id": "117", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Work delegation", "id": "118", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Work estimation", "id": "119", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Work Planning", "id": "120", "tags": "ability", "techtags": "", "level": "" },
    { "name": "WPF", "id": "121", "tags": "knowledge, experience", "techtags": "Windows Solutions, Backend, Frontend", "level": "1" },


];