export interface ISkill {
    name: string;
    tags: string;
    techtags: string;
    level: string;
}
export const mySkills: ISkill[] = [
    { "name": "Accountability", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Agile methodologies", "tags": "methodology", "techtags": "", "level": "" },
    { "name": "Azure DevOps", "tags": "tool", "techtags": "DevOps", "level": "1" },
    { "name": "Azure Fundamentals", "tags": "knowledge", "techtags": "Cloud Solutions", "level": "2" },
    { "name": "Azure RGs", "tags": "experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Azure VMs", "tags": "experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Big picture", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Bitbucket", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Business Analysis", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Business Operations", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "C#", "tags": "Programming Language", "techtags": "Backend", "level": "3" },
    { "name": "Calling out scopecreeps", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Can be diplomatic", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Can be direct", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Can be Friendly", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Client focus", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Confluence", "tags": "tool", "techtags": "", "level": "2" },
    { "name": "Creative problem solving", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Creative troubleshooting", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Critical issue resolution", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Critical thinking", "tags": "quality", "techtags": "", "level": "" },
    { "name": "CSS", "tags": "knowledge, experience, styling language", "techtags": "Frontend", "level": "1" },
    { "name": "Curiosity", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Deliverable scope knowledge", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Detail level", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Documentation", "tags": "ability", "techtags": "", "level": "" },
    { "name": "DR", "tags": "knowledge, experience", "techtags": "Operations", "level": "1" },
    { "name": "Eagerness", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Emotional intelligence", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Empathy", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "English", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Ergonomics", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Estimate collaboration", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Ethics", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Excel", "tags": "tool", "techtags": "Foundation", "level": "3" },
    { "name": "Excitement", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Extreme ownership", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Finance and Accounting", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "Firmness", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Flagging operational issues", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Flagging project issues", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Focus", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Git", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Google docs", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Google Maps API", "tags": "tool, R&D", "techtags": "Frontend", "level": "2" },
    { "name": "Google sheets", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "GraphQL", "tags": "knowledge", "techtags": "Integration", "level": "1" },
    { "name": "High level documentation", "tags": "ability", "techtags": "Solution Architecture", "level": "2" },
    { "name": "Hybrid", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Iaas", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "IIS", "tags": "knowledge, experience", "techtags": "Web Solutions", "level": "1" },
    { "name": "Integration", "tags": "knowledge, experience", "techtags": "Integration", "level": "2" },
    { "name": "Integration Platforms", "tags": "knowledge, experience", "techtags": "Integration", "level": "1" },
    { "name": "Integration testing", "tags": "knowledge, experience", "techtags": "Integration", "level": "1" },
    { "name": "Issue triaging", "tags": "ability", "techtags": "", "level": "" },
    { "name": "JavaScript", "tags": "Programming Language", "techtags": "Frontend, Backend", "level": "3" },
    { "name": "Jira", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "JQuery", "tags": "tech library, knowledge, experience", "techtags": "Frontend", "level": "1" },
    { "name": "Kanban", "tags": "tool", "techtags": "", "level": "" },
    { "name": "Kendo UI", "tags": "tech library, knowledge, experience", "techtags": "Frontend", "level": "2" },
    { "name": "Laziness", "tags": "quality", "techtags": "", "level": "" },
    { "name": "Leadership", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Lean", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "Learning to play guitar", "tags": "ability, hobby", "techtags": "", "level": "" },
    { "name": "Learning to sing", "tags": "ability, hobby", "techtags": "", "level": "" },
    { "name": "Legal", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Management", "tags": "knowledge", "techtags": "", "level": "" },
    { "name": "Microservices", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Mssql server", "tags": "software, knowledge, experience", "techtags": "Data Management", "level": "2" },
    { "name": "MVC", "tags": "knowledge, experience", "techtags": "Architectural Patterns", "level": "2" },
    { "name": "MVVM", "tags": "knowledge, experience", "techtags": "Architectural Patterns", "level": "2" },
    { "name": "New relic", "tags": "tool", "techtags": "Infrastructure", "level": "1" },
    { "name": "On call support", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Organizational structure", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Ownership", "tags": "quality, ability", "techtags": "", "level": "" },
    { "name": "Paas", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Pagerduty", "tags": "tool", "techtags": "Operations", "level": "1" },
    { "name": "PoC", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Postman", "tags": "tool", "techtags": "Foundation, Web Solutions, Integration", "level": "1" },
    { "name": "PowerPoint", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Product Development", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Product Support", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Project Management", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Project scope familiarity", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Quality", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Quality Assurance", "tags": "ability", "techtags": "", "level": "" },
    { "name": "R&D", "tags": "ability", "techtags": "", "level": "" },
    { "name": "RACI", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Requirement documentation", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Requirement gathering", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "REST", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "2" },
    { "name": "Role definition", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "Russian", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "SaaS", "tags": "knowledge, experience", "techtags": "Cloud Solutions", "level": "1" },
    { "name": "Scrum", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "Separation of concern", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Snagit", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "SOAP", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "1" },
    { "name": "SoapUI", "tags": "tool", "techtags": "Foundation, Web Solutions, Integration", "level": "1" },
    { "name": "Solution Architecture", "tags": "knowledge, experience", "techtags": "", "level": "1" },
    { "name": "SOW contribution, review", "tags": "knowledge, experience", "techtags": "", "level": "" },
    { "name": "SQL", "tags": "Quering Language", "techtags": "Data Management", "level": "2" },
    { "name": "SQL geography", "tags": "knowledge, experience", "techtags": "Data Management", "level": "1" },
    { "name": "Svn", "tags": "tool", "techtags": "Foundation", "level": "1" },
    { "name": "Team focus", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Tech leadership", "tags": "ability", "techtags": "", "level": "" },
    { "name": "T-sql", "tags": "Quering Language", "techtags": "Data Management", "level": "2" },
    { "name": "Typescript", "tags": "Programming Language", "techtags": "Foundation, Advanced", "level": "2" },
    { "name": "Unit testing", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Visio", "tags": "tool", "techtags": "Solution Architecture", "level": "2" },
    { "name": "Visual Studio", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Visual Studio Code", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Waterfall", "tags": "methodology, knowledge, experience", "techtags": "", "level": "" },
    { "name": "WBS", "tags": "knowledge, experience", "techtags": "Solution Architecture", "level": "1" },
    { "name": "Web API", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "2" },
    { "name": "Web Services", "tags": "knowledge, experience", "techtags": "Web Solutions, Integration", "level": "1" },
    { "name": "Word", "tags": "tool", "techtags": "Foundation", "level": "2" },
    { "name": "Work delegation", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Work estimation", "tags": "ability", "techtags": "", "level": "" },
    { "name": "Work Planning", "tags": "ability", "techtags": "", "level": "" },
    { "name": "WPF", "tags": "knowledge, experience", "techtags": "Windows Solutions, Backend, Frontend", "level": "1" },

];